#!/usr/bin/env bash

instance_name="$2"
oper="$1"
source /etc/jsrvctl/jsrvctl.profile

check_user() {
    if [ -z "${ADMINGROUPS}" ]; then
        echo "ADMINGROUPS environment variable is not set"
        exit 2
    else
        ADMINGROUPS=${ADMINGROUPS// /\\|}
        result=$(groups |grep -w ${ADMINGROUPS} |grep -v grep |wc -l)
        if [[ ${result} -eq  0 ]]; then
            echo "Your username '($(whoami))' must belong to '${ADMINGROUPS}' group to use jsrvctl. Please contact your system administrator."
            exit 3
        fi
    fi
    return 0
}


show_help() {
	echo "Usage: $0 {start|stop|status} {instance_name|all}"
  echo "Help: $0 --help"
	exit 1 
}


check_user
case "${oper}" in
    start)
        echo "start"
        ;;
    stop)
        echo "stop"
        ;;
    status)
        echo "status"
        ;;
    --help)
        show_help
        ;;
    *)
        echo "Unknown operation '${oper}'"  
        show_help
        ;;
esac
